In [8]:
import numpy as np


a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


a[[0, 2], 1:3]


array([[2, 3],
       [8, 9]])

In [9]:
a = np.array([10, 25, 30, 45, 50])
mask = a > 25  # 生成布尔数组 [False, False, True, True, True]
b = a[mask]  # 用布尔数组索引
print(b)  # [30 45 50]


[30 45 50]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = a > 5  # 条件矩阵
b = a[mask]  # 返回满足条件的一维数组
print(b)  # [6 7 8 9]


In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0:2, 0:2] = np.array([[10, 20], [30, 40]])

print(a)


[[10 20  3]
 [30 40  6]
 [ 7  8  9]]
