In [15]:
import numpy as np

table = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(table[:, 1])
print(table[0:2, 2:4])


[ 2  6 10]
[[3 4]
 [7 8]]


In [16]:
scores = np.array([45, 72, 88, 33, 95, 60])
print(scores[scores >= 60])


[72 88 95 60]


In [2]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

b = a[:3]
b[0] = 999
print(a)


[999  20  30  40  50]


In [6]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[2, 1])
print(a[0, 2])
print(a[1, :])
print(a[2, :])
print(a[:, 1])
print(a[0:2, 1:3])


8
3
[4 5 6]
[7 8 9]
[2 5 8]
[[2 3]
 [5 6]]


In [7]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b = a[0:2, 0:2]  # 前两行前两列
b[0, 0] = 999
print(a)


[[999   2   3]
 [  4   5   6]
 [  7   8   9]]


In [10]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a[(0, 2), :]
b[0, 0] = 999
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

a = np.array([10, 25, 30, 45, 50])

b = a[a > 25]


[30 45 50]


In [15]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a[0:2, 1:3] = 0
print(a)


[[1 0 0]
 [4 0 0]
 [7 8 9]]


In [21]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b = a[:, (0, 2)]
b[0, 0] = 0
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[(0, 2), (0, 2)])


[1 9]


In [25]:
import numpy as np

a = np.array([5, 12, 8, 20, 3])

a[a > 10] = 0
print(a)


[5 0 8 0 3]


In [26]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b = a[a > 5]
print(b)


[6 7 8 9]


In [48]:
import numpy as np

a = np.linspace(-3, 3, 11)
b = np.ones((2, 3), dtype=np.int32)
c = np.random.randint(5, 15, b.shape)
d = a[:6].reshape(2, 3) * c + b
print(a, b, c, d)
print(d.shape, d.dtype)


[-3.  -2.4 -1.8 -1.2 -0.6  0.   0.6  1.2  1.8  2.4  3. ] [[1 1 1]
 [1 1 1]] [[13 11 11]
 [ 7  8 10]] [[-38.  -25.4 -18.8]
 [ -7.4  -3.8   1. ]]
(2, 3) float64


In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b + b


array([ 8, 15, 24])

In [ ]:
import numpy as np

np.random.seed(42)
X = np.random.randint(10, 20, (4, 5))
print(X)
Y = X[:2, 1:4]
print(Y)
print()
Y += 100
print(Y)
Z = X[X % 3 == 0]
print(Z)
Z.reshape(2, -1)
print(Z)
print(Z.shape, Z)
print(X)


[[16 13 17 14 16]
 [19 12 16 17 14]
 [13 17 17 12 15]
 [14 11 17 15 11]]
[[13 17 14]
 [12 16 17]]

[[113 117 114]
 [112 116 117]]
[117 114 117  12  15  15]
[117 114 117  12  15  15]
(6,) [117 114 117  12  15  15]
[[ 16 113 117 114  16]
 [ 19 112 116 117  14]
 [ 13  17  17  12  15]
 [ 14  11  17  15  11]]


In [19]:
import numpy as np

x = np.array([0, 1])
w = np.array([0.5, 0.5])
b = -0.7
tmp = np.sum(w * x) + b
print(tmp)


-0.19999999999999996
