In [29]:
import numpy as np

np.random.seed(42)

a = np.random.randint(0, 100, (5, 5))
print(a)
print(f"数组第二行：{a[1,:]}")
print(f"大于50的元素:{a[a>50]}")
a[(0, 4), ((0, 0), (4, 4))] = -1
print(a)


[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
数组第二行：[20 82 86 74 74]
大于50的元素:[51 92 71 60 82 86 74 74 87 99 52 87 63 59]
[[-1 92 14 71 -1]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [-1 63 59 20 -1]]


In [32]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a = np.array([a[2, :], a[1], a[0, :]])
print(a)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [37]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = a[:, 0]  # 取第一列
c = a[0, :]  # 取第一行
print(b.shape)
c.shape


(3,)


(2,)

In [41]:
a = np.arange(12).reshape(3, 4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
a = np.arange(12).reshape(3, 4)
# 数组内容：
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

result = a[1:, [0, 2]]
result[0, 0] = 999
print(result)
print(a)


[[999   6]
 [  8  10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [46]:
a = np.array([1, 2, 3, 4, 5])
mask = a % 2 == 0  # [False, True, False, True, False]
a[mask] = -1
print(mask)  # 将偶数位置赋值为-1
print(a)  # [1, -1, 3, -1, 5]  等等——


[False  True False  True False]
[ 1 -1  3 -1  5]


In [48]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

b = a.reshape(8)  # 行优先展平：1,2,3,4,5,6,7,8
b[0] = 999
print(b)
print(a)  # a[0,0] = 999  —— b是a的视图，共享数据


[999   2   3   4   5   6   7   8]
[[999   2   3   4]
 [  5   6   7   8]]


In [ ]:
import numpy as np

np.random.seed(0)
A = np.random.randint(0, 100, (6, 6))
B = A[[0, 2, 4], :]
C = A[[1, 3, 5], [0, 2, 4]]
print(A)
print(B)
print(C)


[[44 47 64 67 67  9]
 [83 21 36 87 70 88]
 [88 12 58 65 39 87]
 [46 88 81 37 25 77]
 [72  9 20 80 69 79]
 [47 64 82 99 88 49]]
[[44 47 64 67 67  9]
 [88 12 58 65 39 87]
 [72  9 20 80 69 79]]
[83 81 88]


In [ ]:
# 已知二维嵌套列表
data = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

# 需求A：将data转换为3行4列的数组，然后展平为一维数组
# 需求B：将data转置（行列互换），用reshape实现（注意：reshape不能直接做转置，需思考替代方案）


In [12]:
import numpy as np

data = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
tmp = np.array(np.split(data, 4, axis=1))
tmp.reshape(4, 3)


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
# 已知两个矩阵
matrix_a = [[1, 2], [3, 4]]
matrix_b = [[5, 6], [7, 8]]

# 水平拼接后，垂直切分为上下两半


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.concatenate((a, b), axis=1)
d = np.split(c, 2, axis=1)


[[1 2 5 6]
 [3 4 7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [28]:
import numpy as np


def a(x):
    m = np.shape(x)
    if m[0] < 2:
        return IndexError
    else:
        if m[0] % 2 == 0:
            tmp = np.split(x, 2)
            return np.array(np.mean(tmp[0], axis=1), np.mean(tmp[1], axis=1))
        else:
            tmp = np.split(x, (m[0] / 2) + 1)
            return np.array(np.mean(tmp[0], axis=1), np.mean(tmp[1], axis=1))


b = np.array([[1, 2], [3, 4]])
a(b)


TypeError: Cannot construct a dtype from an array

In [27]:
tmp = np.split(b, 2)
print(tmp)
np.mean(tmp[0], axis=1)


[array([[1, 2]]), array([[3, 4]])]


array([1.5])