In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)

print(b + 3)


(2, 3, 3)
18
3
int64
[[[ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)


[1 2 3 4 5 6]


In [ ]:
a = np.ones((3, 3, 3), dtype=np.int64)
b = a[1][1][0:2]
print(b)
b = 3
print(a)
print(b)


[1 1]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
3


In [ ]:
np.linspace(1, 5, 3, dtype=np.int64)


array([1, 3, 5])

In [ ]:
np.random.rand(3, 4)


array([[0.52112731, 0.97930269, 0.78288365, 0.61640625],
       [0.97628332, 0.47140495, 0.41895159, 0.28620736],
       [0.59521329, 0.78752069, 0.2779978 , 0.03443146]])

In [ ]:
np.random.randn(1, 10)


[array([ 1.29658577,  0.8028832 , -0.17958686, -0.31928628,  1.4811621 ,
         1.52673426, -0.59061326,  0.47990911, -0.72191362, -0.42561474])]