In [10]:
import numpy as np

first = np.arange(1, 6)
second = np.linspace(10, 14, 5)
third = second + 10
result = [first, second, third]
print(result)


[array([1, 2, 3, 4, 5]), array([10., 11., 12., 13., 14.]), array([20., 21., 22., 23., 24.])]


In [2]:
import numpy as np

np.random.seed(42)
result = np.random.randint(1, 101, (3, 3))
print(result)


[[52 93 15]
 [72 61 21]
 [83 87 75]]
